version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      web-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /landing
    schedule:
      interval: weekly
    groups:
      landing-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
